version: '3'

services:
  backend:
    build: ./backend
    image: mashgin-cafe-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - app

  app:
    build: ./app
    image: mashgin-cafe-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
