version: '3'

services:
  backend:
    build: ./backend
    image: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - app

#  app:
#    build: ./app
#    image: app
#    ports:
#      - "8080:8080"
#    environment:
#      - NODE_ENV=production
